"""Add auditoria models

Revision ID: 12930bca53d5
Revises: 
Create Date: 2025-09-22 21:52:44.773871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12930bca53d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relatorios_movimentacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('central_id', sa.Integer(), nullable=True),
    sa.Column('almoxarifado_id', sa.Integer(), nullable=True),
    sa.Column('sub_almoxarifado_id', sa.Integer(), nullable=True),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('total_entradas', sa.Integer(), nullable=True),
    sa.Column('total_saidas', sa.Integer(), nullable=True),
    sa.Column('total_transferencias', sa.Integer(), nullable=True),
    sa.Column('total_distribuicoes', sa.Integer(), nullable=True),
    sa.Column('valor_total_entradas', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_total_saidas', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('produtos_mais_movimentados', sa.JSON(), nullable=True),
    sa.Column('usuarios_mais_ativos', sa.JSON(), nullable=True),
    sa.Column('gerado_por_usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_geracao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['almoxarifado_id'], ['almoxarifados.id'], ),
    sa.ForeignKeyConstraint(['central_id'], ['centrais.id'], ),
    sa.ForeignKeyConstraint(['gerado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.ForeignKeyConstraint(['sub_almoxarifado_id'], ['sub_almoxarifados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs_auditoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_nome', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('usuario_nivel', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('recurso', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('recurso_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('descricao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('endpoint', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('metodo_http', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('central_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('almoxarifado_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sub_almoxarifado_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('setor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_hora', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('sucesso', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('erro_detalhes', sa.Text(), nullable=True))
        batch_op.alter_column('acao',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('dados_anteriores',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('dados_novos',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_index('idx_auditoria_tabela_data')
        batch_op.drop_index('ix_logs_auditoria_acao')
        batch_op.drop_index('ix_logs_auditoria_data_acao')
        batch_op.drop_index('ix_logs_auditoria_registro_id')
        batch_op.drop_index('ix_logs_auditoria_tabela')
        batch_op.drop_index('ix_logs_auditoria_usuario_id')
        batch_op.drop_index('idx_auditoria_acao_data')
        batch_op.create_index('idx_auditoria_acao_data', ['acao', 'data_hora'], unique=False)
        batch_op.drop_index('idx_auditoria_usuario_data')
        batch_op.create_index('idx_auditoria_usuario_data', ['usuario_id', 'data_hora'], unique=False)
        batch_op.create_index('idx_auditoria_almoxarifado', ['almoxarifado_id', 'data_hora'], unique=False)
        batch_op.create_index('idx_auditoria_central', ['central_id', 'data_hora'], unique=False)
        batch_op.create_index('idx_auditoria_data', ['data_hora'], unique=False)
        batch_op.create_index('idx_auditoria_recurso', ['recurso', 'recurso_id'], unique=False)
        batch_op.create_foreign_key(None, 'sub_almoxarifados', ['sub_almoxarifado_id'], ['id'])
        batch_op.create_foreign_key(None, 'almoxarifados', ['almoxarifado_id'], ['id'])
        batch_op.create_foreign_key(None, 'centrais', ['central_id'], ['id'])
        batch_op.create_foreign_key(None, 'setores', ['setor_id'], ['id'])
        batch_op.drop_column('tabela')
        batch_op.drop_column('registro_id')
        batch_op.drop_column('data_acao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_auditoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_acao', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('registro_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('tabela', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_auditoria_recurso')
        batch_op.drop_index('idx_auditoria_data')
        batch_op.drop_index('idx_auditoria_central')
        batch_op.drop_index('idx_auditoria_almoxarifado')
        batch_op.drop_index('idx_auditoria_usuario_data')
        batch_op.create_index('idx_auditoria_usuario_data', ['usuario_id', 'data_acao'], unique=False)
        batch_op.drop_index('idx_auditoria_acao_data')
        batch_op.create_index('idx_auditoria_acao_data', ['acao', 'data_acao'], unique=False)
        batch_op.create_index('ix_logs_auditoria_usuario_id', ['usuario_id'], unique=False)
        batch_op.create_index('ix_logs_auditoria_tabela', ['tabela'], unique=False)
        batch_op.create_index('ix_logs_auditoria_registro_id', ['registro_id'], unique=False)
        batch_op.create_index('ix_logs_auditoria_data_acao', ['data_acao'], unique=False)
        batch_op.create_index('ix_logs_auditoria_acao', ['acao'], unique=False)
        batch_op.create_index('idx_auditoria_tabela_data', ['tabela', 'data_acao'], unique=False)
        batch_op.alter_column('user_agent',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('dados_novos',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('dados_anteriores',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('acao',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('erro_detalhes')
        batch_op.drop_column('sucesso')
        batch_op.drop_column('data_hora')
        batch_op.drop_column('setor_id')
        batch_op.drop_column('sub_almoxarifado_id')
        batch_op.drop_column('almoxarifado_id')
        batch_op.drop_column('central_id')
        batch_op.drop_column('metodo_http')
        batch_op.drop_column('endpoint')
        batch_op.drop_column('descricao')
        batch_op.drop_column('recurso_id')
        batch_op.drop_column('recurso')
        batch_op.drop_column('usuario_nivel')
        batch_op.drop_column('usuario_nome')

    op.drop_table('relatorios_movimentacao')
    # ### end Alembic commands ###
